### ISSUE TITLE
Replacing content categories behavior widget

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.contentpage#213]
@maethu I've just discovered that I've implemented a content categories behavior (in custom code) using `collective.z3cform.keywordwidget`:

``` python
from collective.z3cform.keywordwidget.field import Keywords
from ftw.contentpage import _ as _contentpage
from ftw.contentpage.interfaces import ICategorizable
from plone.directives import form
from zope.interface import alsoProvides


class IContentCategories(form.Schema, ICategorizable):

    content_categories = Keywords(
        title=_contentpage(u'label_categories', default=u'Categories'),
        description=_contentpage(u'help_categories',
                                 default=u'Category for contentlisting'),
        index_name='getContentCategories',
        required=False)


alsoProvides(IContentCategories, form.IFormFieldProvider)
```

It looks like this:
![bildschirmfoto 2015-03-01 um 12 40 22](https://cloud.githubusercontent.com/assets/7469/6430568/25cd1c6c-c010-11e4-908b-ae7f163306f3.png)

This does not require defining a vocabulary and has only one field. Might be a better approach than #211.
What do you think?

**Comment by maethu** [comment]
@jone  definitely the better approach, is it possible to protect adding new categories?

**Comment by jone** [comment]
I don't think so, we'd need to add this.
