### ISSUE TITLE
Discuss: Should ftw.contentpage provide Image/File/Link block view?

### ISSUE THREAD

**Issue by maethu** [4teamwork/ftw.contentpage#223]
Currently this is implemented in simplelayout.types.common. 
Since there's no dependency on s.t.c, we sometimes (other pkgs may have a dep.) lose those block representations. 

Question: Should ftw.contentpage provide default Image/File/Link block representation?

@jone @mbaechtold

**Comment by jone** [comment]
I think we should stop using Plone standard types as Blocks.
Blocks should not have workflows, for example, but normal Files might have workflows.
So I'd create blocks for all types in ftw.contentpage in order to replace Plone standard types..

**Comment by maethu** [comment]
ftw.simplelayout is the replacement of this package and all blocks are self-made, no recycled plone content types.
